
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/
  
version: 2.1

commands:
  checkout_code:
    steps:
      - checkout

jobs:
  build:
    <<: *defaults
    steps:
      - checkout_code
      - run: npm i
      - save cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  
  test:
    <<: *defaults
    steps:
      - checkout_code
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  
  analyze:
    <<: *defaults
    steps:
      - checkout_code
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  ci_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
